http:
  routers:
    dashboard:
      rule: "Host(`${TRAEFIK_SUBDOMAIN}.${DOMAIN}`)"
      service: "api@internal"
      middlewares:
        - auth
        - secure-headers
      tls:
        certResolver: myresolver
        options: modern
  
  middlewares:
    auth:
      basicAuth:
        users:
          - "${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD_HASH}"
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"

  # Options TLS renforcées
  tls:
    options:
      modern:
        minVersion: "VersionTLS13"
        sniStrict: true
      default:
        minVersion: "VersionTLS12"
        cipherSuites:
          - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"