services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - traefik_network
    # Ports exposés uniquement en interne, Traefik s'occupe du routing
    expose:
      - "9000"
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.pocs.hachim.fr`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      # la ligne ci-dessous n'est pas nécessaire en cas de wildcard
      # - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik_network:
    external: true
    name: TraefikNetwork_wildcard.pocs.hachim.fr

volumes:
  portainer_data:
    name: portainer_data