[global]
sendAnonymousUsage = false

[log]
level = "DEBUG"
format = "common"

[providers]

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[api]
dashboard = true
debug = false
insecure = true

[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.websecure]
address = ":443"
[entryPoints.mysql]
address = ":3306"
[entryPoints.mysql80]
address = ":3360"
[entryPoints.sftp]
address = ":2222"
[entrypoints.postgres]
address = ":5432"

[certificatesResolvers.letsencrypt.acme]
email = "cregnier@wynd.eu"
storage = "acme.json"
[certificatesResolvers.letsencrypt.acme.httpChallenge]
entryPoint = "web"
